### ISSUE TITLE
'Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://points-bot-api.bookmaker.xyz/get-profile')

### ISSUE THREAD

**Issue by Domenick90** [shamhi/XPointsMakerBot#2]
24-08-20 01:07:00 | WARNING  | 13   - System | Random wait 0-3 sec to authorization!
24-08-20 01:07:00 | INFO     | 32   - System | List [2] session is loaded...
24-08-20 01:07:00 | SUCCESS  | 86   - System | List [2] proxy  download...
24-08-20 01:07:00 | SUCCESS  | 55   - System | List [2] user-agent download...
24-08-20 01:07:07 | INFO     | 96   - Domenick1990    | id [0] | IP: 188.16.49.101 - Yekaterinburg,RU | wait 3 sec
24-08-20 01:07:07 | INFO     | 96   - Domenick990     | id [1] | IP: 188.16.49.101 - Yekaterinburg,RU | wait 2 sec
24-08-20 01:07:10 | SUCCESS  | 105  - Domenick990     | Authorization successful.
Traceback (most recent call last):
  File "/home/osboxes/XPointsMakerBot/main.py", line 32, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/osboxes/XPointsMakerBot/main.py", line 26, in main
    await asyncio.gather(*tasks)
  File "/home/osboxes/XPointsMakerBot/core/registrator.py", line 108, in start
    profile_data = await get_profile(session, index)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/osboxes/XPointsMakerBot/core/registrator.py", line 25, in get_profile
    return await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/aiohttp/client_reqrep.py", line 1176, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://points-bot-api.bookmaker.xyz/get-profile')
osboxes@osboxes:~/XPointsMakerBot$

**Comment by Domenick90** [comment]
Починил. WebInitData должна начинаться на "query_id..."
